apiVersion: v1
kind: ConfigMap
metadata:
  name: knowhow-config
  namespace: {{ .Values.env}}-knowhow
data:
  forgotPassword.uiHost: "{{ .Values.env}}-psknowhow.tools.publicis.sapient.com"
  corsFilterValidOrigin: "{{ .Values.env}}-psknowhow.tools.publicis.sapient.com"
  isRepoToolEnable: "true"
  keystorefile: "/usr/lib/jvm/java-1.8.0-amazon-corretto/jre/lib/security/cacerts"
  spring.data.mongodb.database: "kpidashboard"
  flag.mailWithoutKafka: "false"
  sendGridEnabled: "true"
  spring.kafka.producer.bootstrap-servers: "crs-kafka-0.kafka-cluster.{{ .Values.env}}-knowhow.svc.cluster.local:9092"
  spring.kafka.consumer.bootstrap-servers: "crs-kafka-0.kafka-cluster.{{ .Values.env}}-knowhow.svc.cluster.local:9092"
  KAFKA_CFG_ZOOKEEPER_CONNECT: "crs-zookeeper-0.zookeeper-cluster.{{ .Values.env}}-knowhow.svc.cluster.local:2181,crs-zookeeper-1.zookeeper-cluster.{{ .Values.env}}-knowhow.svc.cluster.local:2181,crs-zookeeper-2.zookeeper-cluster.{{ .Values.env}}-knowhow.svc.cluster.local:2181"
  ZOO_SERVERS: "crs-zookeeper-0.zookeeper-cluster.{{ .Values.env}}-knowhow.svc.cluster.local:2888:3888,crs-zookeeper-1.zookeeper-cluster.{{ .Values.env}}-knowhow.svc.cluster.local:2888:3888,crs-zookeeper-2.zookeeper-cluster.{{ .Values.env}}-knowhow.svc.cluster.local:2888:3888"
