apiVersion: v1
kind: ConfigMap
metadata:
  name: knowhow-config
  namespace: {{ .Values.env}}-knowhow
data:
  forgotPassword.uiHost: "{{ .Values.env}}-psknowhow.tools.publicis.sapient.com"
  corsFilterValidOrigin: "{{ .Values.env}}-psknowhow.tools.publicis.sapient.com"
  isRepoToolEnable: "true"
  keystorefile: "/usr/lib/jvm/java-1.8.0-amazon-corretto/jre/lib/security/cacerts"
  spring.data.mongodb.database: "kpidashboard"
  flag.mailWithoutKafka: "false"
  sendGridEnabled: "true"
  
  