apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-credentials
  namespace: {{ .Values.env}}-knowhow
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: speedtools-azurekeyvault #refers to the SecretStore object
    kind: SecretStore
  target:
    name: knowhow-config-credentials #name of the k8s native secret
    creationPolicy: Owner
  data:
  - secretKey: {{ .Values.env}}knhdbusername
    remoteRef:
      key: {{ .Values.env}}knhdbusername #Azure Vault secret key
  - secretKey: {{ .Values.env}}knhdbpassword
    remoteRef:
      key: {{ .Values.env}}knhdbpassword #Azure Vault secret key
  - secretKey: {{ .Values.env}}knhdbconnectionstring
    remoteRef:
      key: {{ .Values.env}}knhdbconnectionstring #Azure Vault secret key
  - secretKey: {{ .Values.env}}knhdbhost
    remoteRef:
      key: {{ .Values.env}}knhdbhost #Azure Vault secret key
  - secretKey: knowhow-auth-secret
    remoteRef:
      key: knowhow-auth-secret #Azure Vault secret key
  - secretKey: knowhowaesEncryptionKey
    remoteRef:
      key: knowhowaesEncryptionKey
  - secretKey: {{ .Values.env}}-repo-tool-api-key
    remoteRef:
      key: {{ .Values.env}}-repo-tool-api-key
  - secretKey: {{ .Values.env}}-sendgrid-apikey
    remoteRef:
      key: {{ .Values.env}}-sendgrid-apikey
