apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "knowhow-jira-processor.fullname" . }}
  namespace: {{ .Values.env}}-knowhow
  labels:
    {{- include "knowhow-jira-processor.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "knowhow-jira-processor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "knowhow-jira-processor.selectorLabels" . | nindent 8 }}
    spec:
      # initContainers:
      # - name: init-customapi
      #   image: busybox:1.28
      #   command: ['sh', '-c', "until nslookup knowhow-customapi.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for knowhow-customapi; sleep 2; done"]
      # - name: init-ui
      #   image: busybox:1.28
      #   command: ['sh', '-c', "until nslookup knowhow-ui.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for knowhow-ui; sleep 2; done"]
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "knowhow-jira-processor.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{.Values.service.port}}
              protocol: TCP
          env:
            - name: spring.data.mongodb.uri
              valueFrom:
                secretKeyRef:
                  name: knowhow-config-credentials
                  key: {{ .Values.env}}knhdbconnectionstring
            - name: spring.data.mongodb.host
              valueFrom:
                secretKeyRef:
                  name: knowhow-config-credentials
                  key: {{ .Values.env}}knhdbhost
            
            - name: aesEncryptionKey
              valueFrom:
                secretKeyRef:
                  name: knowhow-config-credentials
                  key: knowhowaesEncryptionKey
            - name: auth.secret
              valueFrom:
                secretKeyRef:
                  name: knowhow-config-credentials
                  key: knowhow-auth-secret

            - name: spring.data.mongodb.username
              valueFrom:
                secretKeyRef:
                  name: knowhow-config-credentials
                  key: {{ .Values.env}}knhdbusername
            - name: spring.data.mongodb.password
              valueFrom:
                secretKeyRef:
                  name: knowhow-config-credentials
                  key: {{ .Values.env}}knhdbpassword
            - name: mongock.migration-scan-package
              value: com.publicissapient.kpidashboard.apis.mongock.installation
          envFrom:
          - configMapRef:
              name: {{ .Values.configmapname }}
          livenessProbe:
            tcpSocket:
              port: {{.Values.service.port}}
            initialDelaySeconds: 10   # Wait for 10 seconds before starting probes
            periodSeconds: 5  
          readinessProbe:
            tcpSocket:
              port: {{.Values.service.port}}
            initialDelaySeconds: 10   # Wait for 10 seconds before starting probes
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
