package com.publicissapient.kpidashboard.apis.util;

import com.publicissapient.kpidashboard.common.model.application.dto.FieldMappingDTO;
import java.time.LocalDateTime;
import java.util.List;



public class FieldMappingUtil {

    private FieldMappingUtil() {
        throw new IllegalStateException("Utility class");
    }

    public static void updateFieldMapping(FieldMappingDTO fieldMappingDTO) {
        if (fieldMappingDTO.getCreatedDate() == null) {
            List<String> defectPriority = fieldMappingDTO.getDefectPriority();
            List<String> jiraStatusForDevelopment = fieldMappingDTO.getJiraStatusForDevelopment();
            List<String> jiraDod = fieldMappingDTO.getJiraDod();
            String jiraDefectRejectionStatus = fieldMappingDTO.getJiraDefectRejectionStatus();
            List<String> jiraDefectCountlIssueType = fieldMappingDTO.getJiraDefectCountlIssueType();
            List<String> jiraIssueDeliverdStatus = fieldMappingDTO.getJiraIssueDeliverdStatus();
            List<String> excludeRCAFromFTPR = fieldMappingDTO.getExcludeRCAFromFTPR();
            String[] jiraIssueTypeNames = fieldMappingDTO.getJiraIssueTypeNames();
            List<String> resolutionTypeForRejection = fieldMappingDTO.getResolutionTypeForRejection();
            String jiraLiveStatus = fieldMappingDTO.getJiraLiveStatus();
            List<String> jiraFTPRStoryIdentification = fieldMappingDTO.getJiraFTPRStoryIdentification();
            List<String> jiraIterationCompletionStatusCustomField = fieldMappingDTO.getJiraIterationCompletionStatusCustomField();
            List<String> jiraIterationCompletionTypeCustomField = fieldMappingDTO.getJiraIterationCompletionTypeCustomField();
            String jiraDor = fieldMappingDTO.getJiraDor();
            List<String> jiraIntakeToDorIssueType = fieldMappingDTO.getJiraIntakeToDorIssueType();
            List<String> jiraStoryIdentification = fieldMappingDTO.getJiraStoryIdentification();
            List<String> jiraStatusForInProgress = fieldMappingDTO.getJiraStatusForInProgress();
            List<String> issueStatusExcluMissingWork = fieldMappingDTO.getIssueStatusExcluMissingWork();
            List<String> jiraWaitStatus = fieldMappingDTO.getJiraWaitStatus();
            List<String> jiraBlockedStatus = fieldMappingDTO.getJiraBlockedStatus();
            String jiraIncludeBlockedStatus = fieldMappingDTO.getJiraIncludeBlockedStatus();
            List<String> jiraDevDoneStatus = fieldMappingDTO.getJiraDevDoneStatus();
            List<String> jiraQADefectDensityIssueType = fieldMappingDTO.getJiraQADefectDensityIssueType();
            List<String> jiraDefectInjectionIssueType = fieldMappingDTO.getJiraDefectInjectionIssueType();
            String jiraDefectCreatedStatus = fieldMappingDTO.getJiraDefectCreatedStatus();
            List<String> jiraDefectSeepageIssueType = fieldMappingDTO.getJiraDefectSeepageIssueType();
            List<String> jiraDefectRemovalStatus = fieldMappingDTO.getJiraDefectRemovalStatus();
            List<String> jiraDefectRemovalIssueType = fieldMappingDTO.getJiraDefectRemovalIssueType();
            List<String> jiraSprintCapacityIssueType = fieldMappingDTO.getJiraSprintCapacityIssueType();
            List<String> jiraDefectRejectionlIssueType = fieldMappingDTO.getJiraDefectRejectionlIssueType();
            List<String> jiraStatusForQa = fieldMappingDTO.getJiraStatusForQa();
            String storyFirstStatus = fieldMappingDTO.getStoryFirstStatus();
            List<String> jiraFtprRejectStatus = fieldMappingDTO.getJiraFtprRejectStatus();
            List<String> jiraDefectClosedStatus = fieldMappingDTO.getJiraDefectClosedStatus();
            List<String> jiraDefectDroppedStatus = fieldMappingDTO.getJiraDefectDroppedStatus();
            List<String> jiraAcceptedInRefinement = fieldMappingDTO.getJiraAcceptedInRefinement();
            List<String> jiraReadyForRefinement = fieldMappingDTO.getJiraReadyForRefinement();
            List<String> jiraRejectedInRefinement = fieldMappingDTO.getJiraRejectedInRefinement();
            String readyForDevelopmentStatus = fieldMappingDTO.getReadyForDevelopmentStatus();

            fieldMappingDTO.setDefectPriorityKPI135(defectPriority);
            fieldMappingDTO.setDefectPriorityKPI14(defectPriority);
            fieldMappingDTO.setDefectPriorityQAKPI111(defectPriority);
            fieldMappingDTO.setDefectPriorityKPI82(defectPriority);
            fieldMappingDTO.setDefectPriorityKPI133(defectPriority);
            fieldMappingDTO.setJiraIssueTypeNamesAVR(jiraIssueTypeNames);
            fieldMappingDTO.setJiraStatusForDevelopmentAVR(jiraStatusForDevelopment);
            fieldMappingDTO.setJiraStatusForDevelopmentKPI82(jiraStatusForDevelopment);
            fieldMappingDTO.setJiraStatusForDevelopmentKPI135(jiraStatusForDevelopment);
            fieldMappingDTO.setJiraDefectInjectionIssueTypeKPI14(jiraDefectInjectionIssueType);
            fieldMappingDTO.setJiraDodKPI14(jiraDod);
            fieldMappingDTO.setJiraDodQAKPI111(jiraDod);
            fieldMappingDTO.setJiraDodKPI3(jiraDod);
            fieldMappingDTO.setJiraDodKPI127(jiraDod);
            fieldMappingDTO.setJiraDodKPI152(jiraDod);
            fieldMappingDTO.setJiraDodKPI151(jiraDod);
            fieldMappingDTO.setJiraDefectCreatedStatusKPI14(jiraDefectCreatedStatus);
            fieldMappingDTO.setJiraDefectRejectionStatusAVR(jiraDefectRejectionStatus);
            fieldMappingDTO.setJiraDefectRejectionStatusKPI28(jiraDefectRejectionStatus);
            fieldMappingDTO.setJiraDefectRejectionStatusKPI34(jiraDefectRejectionStatus);
            fieldMappingDTO.setJiraDefectRejectionStatusKPI37(jiraDefectRejectionStatus);
            fieldMappingDTO.setJiraDefectRejectionStatusKPI35(jiraDefectRejectionStatus);
            fieldMappingDTO.setJiraDefectRejectionStatusKPI82(jiraDefectRejectionStatus);
            fieldMappingDTO.setJiraDefectRejectionStatusKPI135(jiraDefectRejectionStatus);
            fieldMappingDTO.setJiraDefectRejectionStatusKPI133(jiraDefectRejectionStatus);
            fieldMappingDTO.setJiraDefectRejectionStatusRCAKPI36(jiraDefectRejectionStatus);
            fieldMappingDTO.setJiraDefectRejectionStatusKPI14(jiraDefectRejectionStatus);
            fieldMappingDTO.setJiraDefectRejectionStatusQAKPI111(jiraDefectRejectionStatus);
            fieldMappingDTO.setJiraDefectRejectionStatusKPI152(jiraDefectRejectionStatus);
            fieldMappingDTO.setJiraDefectRejectionStatusKPI151(jiraDefectRejectionStatus);
            fieldMappingDTO.setJiraIssueTypeKPI35(jiraDefectSeepageIssueType);
            fieldMappingDTO.setJiraDefectRemovalStatusKPI34(jiraDefectRemovalStatus);
            fieldMappingDTO.setJiraDefectRemovalIssueTypeKPI34(jiraDefectRemovalIssueType);
            fieldMappingDTO.setJiraIssueTypeKPI37(jiraDefectRejectionlIssueType);
            fieldMappingDTO.setJiraSprintCapacityIssueTypeKpi46(jiraSprintCapacityIssueType);
            fieldMappingDTO.setJiraDefectCountlIssueTypeKPI28(jiraDefectCountlIssueType);
            fieldMappingDTO.setJiraDefectCountlIssueTypeKPI36(jiraDefectCountlIssueType);
            fieldMappingDTO.setJiraIssueDeliverdStatusKPI138(jiraIssueDeliverdStatus);
            fieldMappingDTO.setJiraIssueDeliverdStatusAVR(jiraIssueDeliverdStatus);
            fieldMappingDTO.setJiraIssueDeliverdStatusKPI126(jiraIssueDeliverdStatus);
            fieldMappingDTO.setJiraIssueDeliverdStatusKPI82(jiraIssueDeliverdStatus);
            fieldMappingDTO.setJiraDorKPI3(jiraDor);
            fieldMappingDTO.setJiraIssueTypeKPI3(jiraIntakeToDorIssueType);
            fieldMappingDTO.setStoryFirstStatusKPI3(storyFirstStatus);
            fieldMappingDTO.setStoryFirstStatusKPI148(storyFirstStatus);
            fieldMappingDTO.setJiraStoryIdentificationKpi40(jiraStoryIdentification);
            fieldMappingDTO.setJiraStoryIdentificationKPI129(jiraStoryIdentification);
            fieldMappingDTO.setJiraDefectClosedStatusKPI137(jiraDefectClosedStatus);
            fieldMappingDTO.setJiraKPI82StoryIdentification(jiraFTPRStoryIdentification);
            fieldMappingDTO.setJiraKPI135StoryIdentification(jiraFTPRStoryIdentification);
            fieldMappingDTO.setJiraLiveStatusKPI3(jiraLiveStatus);
            fieldMappingDTO.setJiraLiveStatusLTK(jiraLiveStatus);
            fieldMappingDTO.setJiraLiveStatusNOPK(jiraLiveStatus);
            fieldMappingDTO.setJiraLiveStatusNOSK(jiraLiveStatus);
            fieldMappingDTO.setJiraLiveStatusNORK(jiraLiveStatus);
            fieldMappingDTO.setJiraLiveStatusOTA(jiraLiveStatus);
            fieldMappingDTO.setJiraLiveStatusKPI127(jiraLiveStatus);
            fieldMappingDTO.setJiraLiveStatusKPI152(jiraLiveStatus);
            fieldMappingDTO.setJiraLiveStatusKPI151(jiraLiveStatus);
            fieldMappingDTO.setExcludeRCAFromKPI82(excludeRCAFromFTPR);
            fieldMappingDTO.setExcludeRCAFromKPI135(excludeRCAFromFTPR);
            fieldMappingDTO.setExcludeRCAFromKPI14(excludeRCAFromFTPR);
            fieldMappingDTO.setExcludeRCAFromQAKPI111(excludeRCAFromFTPR);
            fieldMappingDTO.setExcludeRCAFromKPI133(excludeRCAFromFTPR);
            fieldMappingDTO.setResolutionTypeForRejectionAVR(resolutionTypeForRejection);
            fieldMappingDTO.setResolutionTypeForRejectionKPI28(resolutionTypeForRejection);
            fieldMappingDTO.setResolutionTypeForRejectionKPI34(resolutionTypeForRejection);
            fieldMappingDTO.setResolutionTypeForRejectionKPI37(resolutionTypeForRejection);
            fieldMappingDTO.setResolutionTypeForRejectionKPI35(resolutionTypeForRejection);
            fieldMappingDTO.setResolutionTypeForRejectionKPI82(resolutionTypeForRejection);
            fieldMappingDTO.setResolutionTypeForRejectionKPI135(resolutionTypeForRejection);
            fieldMappingDTO.setResolutionTypeForRejectionKPI133(resolutionTypeForRejection);
            fieldMappingDTO.setResolutionTypeForRejectionRCAKPI36(resolutionTypeForRejection);
            fieldMappingDTO.setResolutionTypeForRejectionKPI14(resolutionTypeForRejection);
            fieldMappingDTO.setResolutionTypeForRejectionQAKPI111(resolutionTypeForRejection);
            fieldMappingDTO.setJiraQAKPI111IssueType(jiraQADefectDensityIssueType);
            fieldMappingDTO.setJiraStatusForQaKPI135(jiraStatusForQa);
            fieldMappingDTO.setJiraStatusForQaKPI82(jiraStatusForQa);
            fieldMappingDTO.setJiraStatusForQaKPI148(jiraStatusForQa);
            fieldMappingDTO.setJiraStatusForInProgressKPI122(jiraStatusForInProgress);
            fieldMappingDTO.setJiraStatusForInProgressKPI145(jiraStatusForInProgress);
            fieldMappingDTO.setJiraStatusForInProgressKPI125(jiraStatusForInProgress);
            fieldMappingDTO.setJiraStatusForInProgressKPI128(jiraStatusForInProgress);
            fieldMappingDTO.setJiraStatusForInProgressKPI123(jiraStatusForInProgress);
            fieldMappingDTO.setJiraStatusForInProgressKPI119(jiraStatusForInProgress);
            fieldMappingDTO.setJiraStatusForInProgressKPI148(jiraStatusForInProgress);
            fieldMappingDTO.setIssueStatusExcluMissingWorkKPI124(issueStatusExcluMissingWork);
            fieldMappingDTO.setJiraDevDoneStatusKPI119(jiraDevDoneStatus);
            fieldMappingDTO.setJiraDevDoneStatusKPI145(jiraDevDoneStatus);
            fieldMappingDTO.setJiraDevDoneStatusKPI128(jiraDevDoneStatus);
            fieldMappingDTO.setJiraWaitStatusKPI131(jiraWaitStatus);
            fieldMappingDTO.setJiraBlockedStatusKPI131(jiraBlockedStatus);
            fieldMappingDTO.setJiraIncludeBlockedStatusKPI131(jiraIncludeBlockedStatus);
            fieldMappingDTO.setJiraFtprRejectStatusKPI135(jiraFtprRejectStatus);
            fieldMappingDTO.setJiraFtprRejectStatusKPI82(jiraFtprRejectStatus);
            fieldMappingDTO.setJiraIterationCompletionStatusKPI135(jiraIterationCompletionStatusCustomField);
            fieldMappingDTO.setJiraIterationCompletionStatusKPI122(jiraIterationCompletionStatusCustomField);
            fieldMappingDTO.setJiraIterationCompletionStatusKPI75(jiraIterationCompletionStatusCustomField);
            fieldMappingDTO.setJiraIterationCompletionStatusKPI145(jiraIterationCompletionStatusCustomField);
            fieldMappingDTO.setJiraIterationCompletionStatusKPI140(jiraIterationCompletionStatusCustomField);
            fieldMappingDTO.setJiraIterationCompletionStatusKPI132(jiraIterationCompletionStatusCustomField);
            fieldMappingDTO.setJiraIterationCompletionStatusKPI136(jiraIterationCompletionStatusCustomField);
            fieldMappingDTO.setJiraIterationCompletionStatusKPI140(jiraIterationCompletionStatusCustomField);
            fieldMappingDTO.setJiraIterationCompletionStatusKpi72(jiraIterationCompletionStatusCustomField);
            fieldMappingDTO.setJiraIterationCompletionStatusKpi39(jiraIterationCompletionStatusCustomField);
            fieldMappingDTO.setJiraIterationCompletionStatusKpi5(jiraIterationCompletionStatusCustomField);
            fieldMappingDTO.setJiraIterationCompletionStatusKPI124(jiraIterationCompletionStatusCustomField);
            fieldMappingDTO.setJiraIterationCompletionStatusKPI123(jiraIterationCompletionStatusCustomField);
            fieldMappingDTO.setJiraIterationCompletionStatusKPI125(jiraIterationCompletionStatusCustomField);
            fieldMappingDTO.setJiraIterationCompletionStatusKPI120(jiraIterationCompletionStatusCustomField);
            fieldMappingDTO.setJiraIterationCompletionStatusKPI128(jiraIterationCompletionStatusCustomField);
            fieldMappingDTO.setJiraIterationCompletionStatusKPI134(jiraIterationCompletionStatusCustomField);
            fieldMappingDTO.setJiraIterationCompletionStatusKPI133(jiraIterationCompletionStatusCustomField);
            fieldMappingDTO.setJiraIterationCompletionStatusKPI119(jiraIterationCompletionStatusCustomField);
            fieldMappingDTO.setJiraIterationCompletionStatusKPI131(jiraIterationCompletionStatusCustomField);
            fieldMappingDTO.setJiraIterationCompletionStatusKPI138(jiraIterationCompletionStatusCustomField);
            fieldMappingDTO.setJiraIterationIssuetypeKPI122(jiraIterationCompletionTypeCustomField);
            fieldMappingDTO.setJiraIterationIssuetypeKPI138(jiraIterationCompletionTypeCustomField);
            fieldMappingDTO.setJiraIterationIssuetypeKPI131(jiraIterationCompletionTypeCustomField);
            fieldMappingDTO.setJiraIterationIssuetypeKPI128(jiraIterationCompletionTypeCustomField);
            fieldMappingDTO.setJiraIterationIssuetypeKPI134(jiraIterationCompletionTypeCustomField);
            fieldMappingDTO.setJiraIterationIssuetypeKPI145(jiraIterationCompletionTypeCustomField);
            fieldMappingDTO.setJiraIterationIssuetypeKpi72(jiraIterationCompletionTypeCustomField);
            fieldMappingDTO.setJiraIterationIssuetypeKPI119(jiraIterationCompletionTypeCustomField);
            fieldMappingDTO.setJiraIterationIssuetypeKpi5(jiraIterationCompletionTypeCustomField);
            fieldMappingDTO.setJiraIterationIssuetypeKPI75(jiraIterationCompletionTypeCustomField);
            fieldMappingDTO.setJiraIterationIssuetypeKPI123(jiraIterationCompletionTypeCustomField);
            fieldMappingDTO.setJiraIterationIssuetypeKPI125(jiraIterationCompletionTypeCustomField);
            fieldMappingDTO.setJiraIterationIssuetypeKPI120(jiraIterationCompletionTypeCustomField);
            fieldMappingDTO.setJiraIterationIssuetypeKPI124(jiraIterationCompletionTypeCustomField);
            fieldMappingDTO.setJiraDefectDroppedStatusKPI127(jiraDefectDroppedStatus);
            fieldMappingDTO.setJiraAcceptedInRefinementKPI139(jiraAcceptedInRefinement);
            fieldMappingDTO.setJiraReadyForRefinementKPI139(jiraReadyForRefinement);
            fieldMappingDTO.setJiraRejectedInRefinementKPI139(jiraRejectedInRefinement);
            fieldMappingDTO.setReadyForDevelopmentStatusKPI138(readyForDevelopmentStatus);
            fieldMappingDTO.setCreatedDate(LocalDateTime.now());
        }
    }
}
