apiVersion: v1
kind: Service
metadata:
  name: azure-board-processor
  namespace: {{ .Values.env}}-knowhow
  labels:
    {{- include "knowhow-azure-board-processor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "knowhow-azure-board-processor.selectorLabels" . | nindent 4 }}
