# trigger:
# - azure-devops

parameters:
- name: BUILD
  type: string
  default: 'API'
  values:
  - 'API'
  - 'UI'
  - 'Processor'
  - 'ALL'
- name: PUSH_TO_DOCKER_REGISTRY
  type: string
  default: 'YES'
  values:
  - 'YES'
  - 'NO'

pool:
      vmImage: 'ubuntu-latest'

stages:
- stage: API_BUILD
  condition: or(eq('${{ parameters.BUILD }}', 'API'), eq('${{ parameters.BUILD }}', 'ALL'))

  jobs:
  - job: Capturing_Version

    variables:
      overrideValues: ''

    steps:
    - checkout: self

    - script: |
        echo "BUILDING: ${{ parameters.BUILD }}"
        echo "Capturing Version"
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "Version from pom.xml: $VERSION"        
        # echo "##vso[task.setvariable variable=overrideValues]image.tag=$VERSION"
        echo "##vso[task.setvariable variable=overrideValues]$VERSION"
  
  - job: RUNNING_TEST
    displayName: 'Running Tests'
    dependsOn: Capturing_Version

    steps:

    - task: Maven@3
      displayName: 'Run Maven build'
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean install -Pcustomapi'
        publishJUnitResults: true
    
    - script: |
        docker save -o $(Build.ArtifactStagingDirectory)/customapi.tar customapi:$VERSION
      displayName: 'Save Docker image'

    - publish: $(Build.ArtifactStagingDirectory)/
      artifact: customapi-image
    
    - publish: $(System.DefaultWorkingDirectory)/
      artifact: customapi-artifacts

    - publish: /home/vsts/.m2
      artifact: customapi-pipeline-artifacts

  - job: SONAR_ANALYSIS
    displayName: 'Running Sonar'
    dependsOn: RUNNING_TEST

    steps:
    - download: current
      artifact: customapi-artifacts

    - download: current
      artifact: customapi-pipeline-artifacts

    - task: PublishCodeCoverageResults@1
      displayName: 'Publising Code Coverage'
      inputs:
        codeCoverageTool: 'JaCoCo'  # Specify JaCoCo as the code coverage tool.
        summaryFileLocation: '$(Agent.BuildDirectory)/customapi-artifacts/customapi/target/site/jacoco/jacoco.xml'
        reportDirectory: '$(Agent.BuildDirectory)/customapi-artifacts/customapi/target/site/jacoco/'

    - task: SonarQubePrepare@5
      displayName: 'Prepare Analysis Configuration'
      inputs:
        SonarQube: 'sonar-qube-sc' # Name of the SonarQube service connection
        scannerMode: 'Other'
        extraProperties: |
          sonar.projectVersion=$(overrideValues)
          sonar.projectName=ENGINEERING.KPIDASHBOARD.CUSTOMAPI
          sonar.projectKey=ENGINEERING.KPIDASHBOARD.CUSTOMAPI
          sonar.branch.name=$(Build.SourceBranchName)
          sonar.java.binaries=$(Agent.BuildDirectory)/customapi-artifacts/customapi/target/classes
          # sonar.jacoco.reportPath=$(Agent.BuildDirectory)/customapi-artifacts/customapi/target/jacoco.exec
          sonar.coverage.jacoco.xmlReportPaths=$(Agent.BuildDirectory)/customapi-artifacts/customapi/target/site/jacoco/jacoco.xml
          # sonar.qualitygate.wait=true
          # sonar.qualitygate.timeout=300
          # sonar.sources=customapi/pom.xml
          # sonar.language=java
          sonar.sourceEncoding=UTF-8
      enabled: true
    - script: 'mvn sonar:sonar -Dmaven.repo.local=$(Agent.BuildDirectory)/customapi-pipeline-artifacts/repository -f customapi/pom.xml'
      displayName: 'Run SonarQube analysis'
    
    - task: SonarQubePublish@5
      displayName: Publish Quality Gate Result
      inputs:
        pollingTimeoutSec: '300'
    # - script: |
    #     result=$(sonar-scanner -Dsonar.login=$(SonarQubeToken) -Dsonar.projectKey=ENGINEERING.KPIDASHBOARD.CUSTOMAPI -Dsonar.host.url=https://tools.publicis.sapient.com/sonar -Dsonar.qualitygate.show=true)
    #     if [[ "$result" =~ QUALITY_GATE_STATUS=ERROR ]]; then
    #       echo "Quality Gate check failed."
    #       exit 1
    #     fi
    #   displayName: 'Check Quality Gate Status'
    #   continueOnError: false

- stage: UI_Build
  condition: or(eq('${{ parameters.BUILD }}', 'UI'), eq('${{ parameters.BUILD }}', 'ALL'))

  jobs:
  - job: Capturing_Version
    displayName: 'Checking Version'
    variables:
      overrideValues: ''

    steps:
    - checkout: self

    - script: |
        echo "BUILDING: ${{ parameters.BUILD }}"
        echo "Capturing Version"
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "Version from pom.xml: $VERSION"        
        # echo "##vso[task.setvariable variable=overrideValues]image.tag=$VERSION"
        echo "##vso[task.setvariable variable=overrideValues]$VERSION"
  
  - job: RUNNING_TEST
    displayName: 'Running Tests'
    dependsOn: Capturing_Version

    steps:
    - script: |
        cd UI/
        echo "npm version "
        npm -v
        echo "node -v"
        node -v
        npm cache clean --force
        npm install
        npm install --save-dev @angular-devkit/build-angular@14.2.11
        npm run build
        mkdir -p build
        cp -r dist/dashboard/* build/
        chmod -R 775 build
        cd build
        tar -czvf ui2.tar *
        mv ui2.tar ../nginx/files
        rm -rf build

  - job: CHECKING_COVERAGE
    displayName: 'Generating Coverage report'
    dependsOn: RUNNING_TEST

    steps:
    - script: |
        cd UI
        npm install --save-dev @angular-devkit/build-angular@14.2.10
        sudo npm test 
        sudo sed -i 's|SF:$(Agent.BuildDirectory)/UI|SF:|g' coverage/report-lcov/lcov.info
    
    - publish: $(System.DefaultWorkingDirectory)/UI
      artifact: UI-artifacts
  
    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: 'cobertura' # or 'jacoco' depending on the format of your coverage report
        summaryFileLocation: '$(Agent.BuildDirectory)/UI-artifacts/coverage/report-lcov/lcov.info' # adjust this path based on the actual path of your coverage report
        reportDirectory: '$(Agent.BuildDirectory)/UI-artifacts/coverage/report-html/'
        failIfCoverageEmpty: false
  
  - job: SONARQUBE_ANALYSIS
    displayName: 'SonarQube Code Analysis'
    dependsOn: CHECKING_COVERAGE

    steps:
    - download: current
      artifact: UI-artifacts

    - task: SonarQubePrepare@5
      displayName: 'Prepare Analysis Configuration'
      inputs:
        SonarQube: 'sonar-qube-sc' # Name of the SonarQube service connection
        scannerMode: 'Other'
        extraProperties: |
          sonar.projectKey=ENGINEERING.KPIDASHBOARD.UI
          sonar.projectName=ENGINEERING.KPIDASHBOARD.UI
          sonar.branch.name=$(Build.SourceBranchName)
          sonar.projectVersion=1.0
          sonar.sources=src
          sonar.sourceEncoding=UTF-8
          sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/src/app/component/**/*.ts,**/src/test.ts
          sonar.tests=src
          sonar.test.inclusions=**/*.spec.ts
          sonar.ts.tslintconfigpath=tslint.json
          sonar.typescript.lcov.reportPaths=$(Agent.BuildDirectory)/UI-artifacts/coverage/report-lcov/lcov.info
          sonar.coverage.exclusions=**/app/config/project-config/project-config.component.ts,**/app/config/project-config/project-config.route.ts,**/main.ts,**/karma.conf.js,**/app/external-url.directive.ts,**/environments/*,**/app/dashboard/maturity/*,**/app/services/*,**/app/component/**/*,**/app/model/*,**/app/config/engg-maturity-config/*.ts,**/app/config/shared/**/*,**/app/module/*,**/app/utils/*
          sonar.cpd.exclusions=**/app/dashboard/quality/*.html,**/app/dashboard/productivity/*.html,**/app/dashboard/executive/*.html
      enabled: true
    - script: 'cd UI && npm install -D sonarqube-scanner && npm run sonar'
      displayName: 'Run SonarQube analysis'

- stage: Processor_Build
  condition: or(eq('${{ parameters.BUILD }}', 'Processor'), eq('${{ parameters.BUILD }}', 'ALL'))

  jobs:
  - job: Capturing_Version

    variables:
      overrideValues: ''

    steps:
    - checkout: self

    - script: |
        echo "BUILDING: ${{ parameters.BUILD }}"
        echo "Capturing Version"
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "Version from pom.xml: $VERSION"        
        # echo "##vso[task.setvariable variable=overrideValues]image.tag=$VERSION"
        echo "##vso[task.setvariable variable=overrideValues]$VERSION"
  
  - job: RUNNING_TEST
    displayName: 'Running Tests'
    dependsOn: Capturing_Version

    steps:

    - task: Maven@3
      displayName: 'Run Jira build'
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean install -Pjira-processor'
        publishJUnitResults: true
        # sonarQubeRunAnalysis: true
    
    - task: Maven@3
      displayName: 'Run devops build'
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean install -Pdevops-processor'
        publishJUnitResults: true

    - task: Maven@3
      displayName: 'Run az board build'
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean install -Pazure-board-processor'
        publishJUnitResults: true

    - task: Maven@3
      displayName: 'Run az pipeline build'
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean install -Pazure-pipeline-repo'
        publishJUnitResults: true    
    
    - publish: $(System.DefaultWorkingDirectory)/
      artifact: processor-artifacts

    - publish: /home/vsts/.m2
      artifact: processor-pipeline-artifacts

  - job: SONAR_ANALYSIS
    displayName: 'Running Sonar'
    dependsOn: RUNNING_TEST

    steps:
    - download: current
      artifact: processor-artifacts

    - download: current
      artifact: processor-pipeline-artifacts

    # - task: PublishCodeCoverageResults@1
    #   displayName: 'Publising Code Coverage jira pipeline'
    #   inputs:
    #     codeCoverageTool: 'JaCoCo'  # Specify JaCoCo as the code coverage tool.
    #     summaryFileLocation: '$(Agent.BuildDirectory)/processor-artifacts/processors/jira/target/site/jacoco/jacoco.xml'
    #     reportDirectory: '$(Agent.BuildDirectory)/processor-artifacts/processors/jira/target/site/jacoco/'

    - task: PublishCodeCoverageResults@1
      displayName: 'Publising Code Coverage Azure board'
      inputs:
        codeCoverageTool: 'JaCoCo'  # Specify JaCoCo as the code coverage tool.
        summaryFileLocation: |
          $(Agent.BuildDirectory)/processor-artifacts/processors/*/target/site/jacoco/jacoco.xml
        reportDirectory: '$(Agent.BuildDirectory)/processor-artifacts/processors/*/target/site/jacoco/'
    - task: SonarQubePrepare@5
      displayName: 'Prepare Analysis Configuration'
      inputs:
        SonarQube: 'sonar-qube-sc' # Name of the SonarQube service connection
        scannerMode: 'Other'
        extraProperties: |
          sonar.projectVersion=$(overrideValues)
          sonar.projectName=ENGINEERING.KPIDASHBOARD.PROCESSORS
          sonar.projectKey=ENGINEERING.KPIDASHBOARD.PROCESSORS
          sonar.branch.name=$(Build.SourceBranchName)
          sonar.java.binaries=$(Agent.BuildDirectory)/processor-artifacts/processors/**/target/classes, $(Agent.BuildDirectory)/processor-artifacts/**/target/classes
          # sonar.jacoco.reportPath=$(Agent.BuildDirectory)/processor-artifacts/processors/target/jacoco.exec
          sonar.coverage.jacoco.xmlReportPaths=$(Agent.BuildDirectory)/processor-artifacts/processors/**/target/site/jacoco/jacoco.xml
          # sonar.qualitygate.wait=true
          # sonar.qualitygate.timeout=300
          # sonar.sources=processors/pom.xml
          # sonar.language=java
          sonar.sourceEncoding=UTF-8
      enabled: true
    - script: 'mvn sonar:sonar -Dmaven.repo.local=$(Agent.BuildDirectory)/processor-pipeline-artifacts/repository -f processors/pom.xml'
      displayName: 'Run SonarQube analysis'
    
    - task: SonarQubePublish@5
      displayName: Publish Quality Gate Result
      inputs:
        pollingTimeoutSec: '300'
    