trigger:
- azure-devops

parameters:
- name: deploymentOptions
  type: string
  # default: 'UI'
  values:
  - 'API'
  - 'UI'
  - 'Jira_Processor'
  - 'DevOps_Processor'
  - 'Azure_Board_Processor'
  - 'Azure_Pipeline_Repo'
  - 'ALL'
- name: Environment
  type: string
  default: 'uat'
  values:
  - 'uat'
  - 'prod'

stages:
- stage: API_Deploy
  condition: eq('${{ parameters.deploymentOptions }}', 'API')

  jobs:
  - job: API_Deploy
    pool:
      vmImage: 'ubuntu-latest'

    variables:
      overrideValues: ''

    steps:
    - checkout: self

    - script: |
        echo "Selected Deployment Options: ${{ parameters.deploymentOptions }}"
        echo "Deploying  on: ${{ parameters.Environment }}"
        echo "Deploying API..."
        # Add API deployment steps
        echo "Deploying Helm charts for API..."
        # Extract version from pom.xml
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        # echo "##vso[task.setvariable variable=overrideValues]image.tag=$VERSION"
        echo "Version from pom.xml: $VERSION"
        echo "##vso[task.setvariable variable=overrideValues]$VERSION"
    - task: HelmDeploy@0
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceConnection: '${{ parameters.Environment }}-knowhow-k8s-sc'
        namespace: '${{ parameters.Environment }}-knowhow'
        command: 'upgrade'
        chartType: 'FilePath'
        chartPath: './Kubernetes/knowhow-helm/knowhow-customapi'
        releaseName: 'customapi'
        overrideValues: 'image.tag=$(overrideValues)'
        valueFile: './Kubernetes/knowhow-helm/knowhow-customapi/values.yaml'
      displayName: 'Deploy API'

- stage: UI_Deploy
  condition: eq('${{ parameters.deploymentOptions }}', 'UI')

  jobs:
  - job: UI_Deploy
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self

    - script: |
        echo "Selected Deployment Options: ${{ parameters.deploymentOptions }}"
        echo "${{ parameters.Environment }}"
        echo "Deploying UI..."
        # Add UI deployment steps
        echo "Deploying Helm charts for UI..."
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        # echo "##vso[task.setvariable variable=overrideValues]image.tag=$VERSION"
        echo "Version from pom.xml: $VERSION"
        echo "##vso[task.setvariable variable=overrideValues]$VERSION"

    - task: HelmDeploy@0
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceConnection: '${{ parameters.Environment }}-knowhow-k8s-sc'
        namespace: '${{ parameters.Environment }}-knowhow'
        command: 'upgrade'
        chartType: 'FilePath'
        chartPath: './Kubernetes/knowhow-helm/knowhow-ui'
        releaseName: 'knowhow-ui'
        overrideValues: 'image.tag=$(overrideValues)'
        valueFile: './Kubernetes/knowhow-helm/knowhow-ui/values.yaml'
      displayName: 'Deploy Helm Charts for UI'

- stage: Jira_Processor_Deploy
  condition: eq('${{ parameters.deploymentOptions }}', 'Jira_Processor')

  jobs:
  - job: Jira_Processor_Deploy
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self

    - script: |
        cd processors/jira
        echo "Selected Deployment Options: ${{ parameters.deploymentOptions }}"
        echo "${{ parameters.Environment }}"
        echo "Deploying Jira_Processor..."
        # Add Jira_Processor deployment steps
        echo "Deploying Helm charts for Jira_Processor..."
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        # echo "##vso[task.setvariable variable=overrideValues]image.tag=$VERSION"
        echo "Version from pom.xml: $VERSION"
        echo "##vso[task.setvariable variable=overrideValues]$VERSION"

    - task: HelmDeploy@0
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceConnection: '${{ parameters.Environment }}-knowhow-k8s-sc'
        namespace: '${{ parameters.Environment }}-knowhow'
        command: 'upgrade'
        chartType: 'FilePath'
        chartPath: './Kubernetes/knowhow-helm/knowhow-jira-processor'
        releaseName: 'jira-processor'
        overrideValues: 'image.tag=$(overrideValues)'
        valueFile: './Kubernetes/knowhow-helm/knowhow-jira-processor/values.yaml'
      displayName: 'Deploy Helm Charts for jira-processor'

- stage: DevOps_Processor_Deploy
  condition: eq('${{ parameters.deploymentOptions }}', 'DevOps_Processor')

  jobs:
  - job: DevOps_Processor_Deploy
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self

    - script: |
        echo "Selected Deployment Options: ${{ parameters.deploymentOptions }}"
        echo "${{ parameters.Environment }}"
        echo "Deploying DevOps_Processor..."
        # Add DevOps_Processor deployment steps
        echo "Deploying Helm charts for DevOps_Processor..."
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        # echo "##vso[task.setvariable variable=overrideValues]image.tag=$VERSION"
        echo "Version from pom.xml: $VERSION"
        echo "##vso[task.setvariable variable=overrideValues]$VERSION"

    - task: HelmDeploy@0
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceConnection: '${{ parameters.Environment }}-knowhow-k8s-sc'
        namespace: '${{ parameters.Environment }}-knowhow'
        command: 'upgrade'
        chartType: 'FilePath'
        chartPath: './Kubernetes/knowhow-helm/devops-processor'
        releaseName: 'devops-processor'
        overrideValues: 'image.tag=$(overrideValues)'
        valueFile: './Kubernetes/knowhow-helm/devops-processor/values.yaml'
      displayName: 'Deploy DevOps_Processor'

- stage: Azure_Board_Processor_Deploy
  condition: eq('${{ parameters.deploymentOptions }}', 'Azure_Board_Processor')

  jobs:
  - job: Azure_Board_Processor_Deploy
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self

    - script: |
        echo "Selected Deployment Options: ${{ parameters.deploymentOptions }}"
        echo "${{ parameters.Environment }}"
        echo "Deploying Azure_Board_Processor..."
        # Add Azure_Board_Processor deployment steps
        echo "Deploying Helm charts for Azure_Board_Processor..."
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        # echo "##vso[task.setvariable variable=overrideValues]image.tag=$VERSION"
        echo "Version from pom.xml: $VERSION"
        echo "##vso[task.setvariable variable=overrideValues]$VERSION"

    - task: HelmDeploy@0
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceConnection: '${{ parameters.Environment }}-knowhow-k8s-sc'
        namespace: '${{ parameters.Environment }}-knowhow'
        command: 'upgrade'
        chartType: 'FilePath'
        chartPath: './Kubernetes/knowhow-helm/knowhow-azure-board-processor'
        releaseName: 'azure-board-processor'
        overrideValues: 'image.tag=$(overrideValues)'
        valueFile: './Kubernetes/knowhow-helm/knowhow-azure-board-processor/values.yaml'
      displayName: 'Deploy knowhow-azure-board-processor'

- stage: Azure_Pipeline_Repo_Deploy
  condition: eq('${{ parameters.deploymentOptions }}', 'Azure_Pipeline_Repo')

  jobs:
  - job: Azure_Pipeline_Repo_Deploy
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self

    - script: |
        echo "Selected Deployment Options: ${{ parameters.deploymentOptions }}"
        echo "${{ parameters.Environment }}"
        echo "Deploying Azure_Pipeline_Repo..."
        # Add Azure_Pipeline_Repo deployment steps
        echo "Deploying Helm charts for Azure_Pipeline_Repo..."
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        # echo "##vso[task.setvariable variable=overrideValues]image.tag=$VERSION"
        echo "Version from pom.xml: $VERSION"
        echo "##vso[task.setvariable variable=overrideValues]$VERSION"

    - task: HelmDeploy@0
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceConnection: '${{ parameters.Environment }}-knowhow-k8s-sc'
        namespace: '${{ parameters.Environment }}-knowhow'
        command: 'upgrade'
        chartType: 'FilePath'
        chartPath: './Kubernetes/knowhow-helm/knowhow-azure-pipeline-repo'
        releaseName: 'azure-pipeline-repo'
        overrideValues: 'image.tag=$(overrideValues)'
        valueFile: './Kubernetes/knowhow-helm/knowhow-azure-pipeline-repo/values.yaml'
      displayName: 'Deploy azure-repo'

- stage: Deploy_ALL
  condition: eq('${{ parameters.deploymentOptions }}', 'ALL')

  jobs:
  - job: Deploy_ALL
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self

    - script: |
        echo "Selected Deployment Options: ${{ parameters.deploymentOptions }}"
        echo "${{ parameters.Environment }}"
        echo "Deploying ALL..."
        # Add deployment steps for all options
      displayName: 'Deploy ALL'
