trigger:
- azure-devops

parameters:
- name: deploymentOptions
  type: string
  default: 'ALL'
  values:
  - 'API'
  - 'UI'
  - 'Processor'
  - 'ALL'
- name: Environment
  type: string
  default: 'PreProd'
  values:
  - 'PreProd'
  - 'Prod'

stages:
- stage: API_Deploy
  condition: eq('${{ parameters.deploymentOptions }}', 'API')

  jobs:
  - job: API_Deploy
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self

    - script: |
        echo "Selected Deployment Options: ${{ parameters.deploymentOptions }}"
        echo "${{ parameters.Environment }}"
        echo "Deploying API..."
        # Add API deployment steps
        echo "Deploying Helm charts for API..."
        ls
        # Add Helm deployment steps for API
        # Example: helm upgrade --install customapi ./Kubernetes/knowhow-helm/knowhow-customapi
      displayName: 'Deploy API'

- stage: UI_Deploy
  condition: eq('${{ parameters.deploymentOptions }}', 'UI')

  jobs:
  - job: UI_Deploy
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self

    - script: |
        echo "Selected Deployment Options: ${{ parameters.deploymentOptions }}"
        echo "${{ parameters.Environment }}"
        echo "Deploying UI..."
        # Add UI deployment steps
        echo "Deploying Helm charts for UI..."
        ls
        # Add Helm deployment steps for UI
        # Example: helm upgrade --install customapi ./Kubernetes/knowhow-helm/knowhow-customapi
      displayName: 'Deploy UI'

- stage: Processor_Deploy
  condition: eq('${{ parameters.deploymentOptions }}', 'Processor')

  jobs:
  - job: Processor_Deploy
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self

    - script: |
        echo "Selected Deployment Options: ${{ parameters.deploymentOptions }}"
        echo "${{ parameters.Environment }}"
        echo "Deploying Processor..."
        # Add Processor deployment steps
        echo "Deploying Helm charts for Processor..."
        ls
        # Add Helm deployment steps for Processor
        # Example: helm upgrade --install customapi ./Kubernetes/knowhow-helm/knowhow-customapi
      displayName: 'Deploy Processor'

- stage: Deploy_ALL
  condition: eq('${{ parameters.deploymentOptions }}', 'ALL')

  jobs:
  - job: Deploy_ALL
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self

    - script: |
        echo "Selected Deployment Options: ${{ parameters.deploymentOptions }}"
        echo "${{ parameters.Environment }}"
        echo "Deploying ALL..."
        # Add deployment steps for all options
      displayName: 'Deploy ALL'
