trigger:
- azure-devops

parameters:
- name: deploymentOptions
  type: string
  default: 'ALL'
  values:
  - 'API'
  - 'UI'
  - 'Processor'
  - 'ALL'
- name: Environment
  type: string
  default: 'PreProd'
  values:
  - 'PreProd'
  - 'Prod'

jobs:
- job: deploy
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self

  - script: |
      echo "Selected Deployment Options: ${{ parameters.deploymentOptions }}"
      # Add your deployment steps based on the selected options
      
      if [ "${{ parameters.deploymentOptions }}" == "API" ]; then
          echo "Deploying API..."
          echo "${{parameters.Environment}}"
          # Add API deployment steps
      fi

      if [ "${{ parameters.deploymentOptions }}" == "UI" ]; then
          echo "Deploying UI..."
          # Add UI deployment steps
      fi

      if [ "${{ parameters.deploymentOptions }}" == "Processor" ]; then
          echo "Deploying Processor..."
          # Add Processor deployment steps
      fi

      if [ "${{ parameters.deploymentOptions }}" == "ALL" ]; then
          echo "Deploying ALL..."
          # Add deployment steps for all options
      fi
    displayName: 'Deploy Application'

- stage: deployHelmCharts
  condition: eq('${{ parameters.deploymentOptions }}', 'API')
  jobs:
  - job: deployHelmChartsJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
    - script: |
        echo "Deploying Helm charts for API..."
        # Add Helm deployment steps for API
        # Example: helm upgrade --install customapi ./Kubernetes/knowhow-helm/knowhow-customapi
      displayName: 'Deploy Helm Charts for API'
