trigger:
- azure-devops

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: deploymentType
  displayName: 'Select Deployment Type'
  type: string
  values:
  - 'ui'
  - 'api'
  - 'processor'
  default: 'ui'

stages:
- stage: UI
  displayName: 'UI Deployment'
  condition: eq(variables['deploymentType'], 'ui')
  jobs:
  - job: UI_Deployment
    steps:
    - script: |
        echo "Deploying UI..."
        # Add your UI deployment steps here

- stage: API
  displayName: 'API Deployment'
  condition: eq(variables['deploymentType'], 'api')
  jobs:
  - job: API_Deployment
    steps:
    - script: |
        echo "Deploying API..."
        # Add your API deployment steps here

- stage: Processor
  displayName: 'Processor Deployment'
  condition: eq(variables['deploymentType'], 'processor')
  jobs:
  - job: Processor_Deployment
    steps:
    - script: |
        echo "Deploying Processor..."
        # Add your Processor deployment steps here
