trigger:
- azure-devops

parameters:
- name: deploymentOptions
  type: string
  default: 'ALL'
  values:
  - 'API'
  - 'UI'
  - 'Processor'
  - 'ALL'
- name: Environment
  type: string
  default: 'PreProd'
  values:
  - 'PreProd'
  - 'Prod'

stages:
- stage: deploy
  jobs:
  - job: deployJob
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self

    - script: |
        echo "Selected Deployment Options: ${{ parameters.deploymentOptions }}"
        echo "${{ parameters.Environment }}"
        # Add your deployment steps based on the selected options
        
        if [ "${{ parameters.deploymentOptions }}" == "API" ]; then
            echo "Deploying API..."
            # Add API deployment steps
        fi

        if [ "${{ parameters.deploymentOptions }}" == "UI" ]; then
            echo "Deploying UI..."
            # Add UI deployment steps
        fi

        if [ "${{ parameters.deploymentOptions }}" == "Processor" ]; then
            echo "Deploying Processor..."
            # Add Processor deployment steps
        fi

        if [ "${{ parameters.deploymentOptions }}" == "ALL" ]; then
            echo "Deploying ALL..."
            # Add deployment steps for all options
        fi
      displayName: 'Deploy Application'

- stage: API_Deploy
  dependsOn: deploy
  condition: and(succeeded(), eq('${{ parameters.deploymentOptions }}', 'API'))

  jobs:
  - job: API_Deploy
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - script: |
        echo "Deploying Helm charts for API..."
        ls
        # Add Helm deployment steps for API
        # Example: helm upgrade --install customapi ./Kubernetes/knowhow-helm/knowhow-customapi
      displayName: 'Deploy Helm Charts for API'

- stage: UI_Deploy
  dependsOn: deploy
  condition: and(succeeded(), eq('${{ parameters.deploymentOptions }}', 'UI'))

  jobs:
  - job: UI_Deploy
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - script: |
        echo "Deploying Helm charts for UI..."
        ls
        # Add Helm deployment steps for API
        # Example: helm upgrade --install customapi ./Kubernetes/knowhow-helm/knowhow-customapi
      displayName: 'Deploy Helm Charts for UI'

- stage: Processor_Deploy
  dependsOn: deploy
  condition: and(succeeded(), eq('${{ parameters.deploymentOptions }}', 'Processor'))

  jobs:
  - job: Processor_Deploy
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - script: |
        echo "Deploying Helm charts for Processor..."
        ls
        # Add Helm deployment steps for Processor
        # Example: helm upgrade --install customapi ./Kubernetes/knowhow-helm/knowhow-customapi
      displayName: 'Deploy Helm Charts for Processor'
