trigger:
- azure-devops

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: deploymentType
  displayName: 'Select Deployment Type'
  type: string
  values:
  - 'ui'
  - 'api'
  - 'processor'
  default: 'ui'

# jobs:
# - job: Set_Maven_Version
#   displayName: 'Set Maven Version'
#   steps:
#   - script: |
#       MAVEN_VERSION=$(xmlstarlet sel -t -v "/project/version" pom.xml)
#       echo "##vso[task.setvariable variable=MAVEN_VERSION]$MAVEN_VERSION"
#     displayName: 'Set Maven Version'

# - job: Display_Maven_Version
#   displayName: 'Display Maven Version'
#   steps:
#   - script: |
#       echo "Maven Version: $(MAVEN_VERSION)"
#     displayName: 'Display Maven Version'

stages:

- stage: Java version
  displayName: 'UI vjava version Deployment'
  jobs:
  - job: Version
    steps:
    - script: |
        MAVEN_VERSION=$(xmlstarlet sel -t -v "/project/version" pom.xml)
        echo "##vso[task.setvariable variable=MAVEN_VERSION]$MAVEN_VERSION"
      displayName: 'Set Maven Version'

- stage: Chenking version
  displayName: 'UI version Deployment'
  jobs:
  - job: Version
    steps:
    - script: |
        echo "Maven Version: $(MAVEN_VERSION)"
      displayName: 'Display Maven Version'

- stage: UI
  displayName: 'UI Deployment'
  condition: eq(variables['deploymentType'], 'ui')
  jobs:
  - job: UI_Deployment
    steps:
    - script: |
        echo "Deploying UI..."
        # Add your UI deployment steps here

- stage: API
  displayName: 'API Deployment'
  condition: eq(variables['deploymentType'], 'api')
  jobs:
  - job: API_Deployment
    steps:
    - script: |
        echo "Deploying API..."
        # Add your API deployment steps here

- stage: Processor
  displayName: 'Processor Deployment'
  condition: eq(variables['deploymentType'], 'processor')
  jobs:
  - job: Processor_Deployment
    steps:
    - script: |
        echo "Deploying Processor..."
        # Add your Processor deployment steps here
