trigger:
  branches:
    include:
      - add_pipeline_file

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    ls -al ./
  displayName: 'Test - file listing'
- script: |
    cat ./azure-devops-pipelines/azure-pipelines.yml
  displayName: 'My custom task (shell)'  