apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "debbie-rabbitmq.fullname" . }}
  namespace: {{ .Values.env}}-knowhow
  labels:
    {{- include "debbie-rabbitmq.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "debbie-rabbitmq.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "debbie-rabbitmq.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "debbie-rabbitmq.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: {{ .Values.configmapname }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretname}}
                  key: {{ .Values.env }}debbieuser
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretname}}
                  key: {{.Values.env}}debbiepassword
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretname}}
                  key: {{ .Values.env }}-debbie-db-url
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretname}}
                  key: {{ .Values.env}}-debbie-secret-key
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretname}}
                  key: {{ .Values.env }}rabbitpass
            - name: EMAIL_HOST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretname}}
                  key: debbiemailhostpass
            - name: TENGINE_QUERY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretname}}
                  key: tenginequerypass
            - name: TENGINE_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretname}}
                  key: debbietengineauthtoken
            - name: DEBBIE_INTERNAL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretname}}
                  key: debbieinternalapikey
          ports:
            {{- range $port := .Values.ports }}
            - containerPort: {{ $port }}
            {{- end }}
          readinessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 10   # Wait for 10 seconds before starting probes
            periodSeconds: 5          # Check every 5 seconds
          livenessProbe:
            tcpSocket:
              port: 5672
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
