apiVersion: v1
kind: Service
metadata:
  name: {{ include "debbie-rabbitmq.fullname" . }}
  labels:
    {{- include "debbie-rabbitmq.labels" . | nindent 4 }}
  namespace: {{ .Values.env}}-knowhow
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $servicePort := .Values.servicePorts }}
    - protocol: TCP
      port: {{ $servicePort.port }}
      targetPort: {{ $servicePort.targetPort }}
      name: {{ $servicePort.name }}
    {{- end }}
  selector:
    {{- include "debbie-rabbitmq.selectorLabels" . | nindent 4 }}
