apiVersion: v1
kind: Service
metadata:
  name: devops-processor
  namespace: {{ .Values.env}}-knowhow
  labels:
    app: devops-processor
spec:
  type: {{ .Values.service.type }}
  # ports:
  #   - port: {{ .Values.service.port }}
  #     targetPort: http
  #     protocol: TCP
  #     name: http
  ports:
    {{- range $servicePort := .Values.servicePorts }}
    - protocol: TCP
      port: {{ $servicePort.port }}
      targetPort: {{ $servicePort.targetPort }}
      name: {{ $servicePort.name }}
    {{- end }}
  selector:
    app: devops-processor
