apiVersion: v1
kind: Service
metadata:
  name: {{ include "devops-processor.fullname" . }}
  namespace: {{ .Values.namespace}}
  labels:
    {{- include "devops-processor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  # ports:
  #   - port: {{ .Values.service.port }}
  #     targetPort: http
  #     protocol: TCP
  #     name: http
  ports:
    {{- range $servicePort := .Values.servicePorts }}
    - protocol: TCP
      port: {{ $servicePort.port }}
      targetPort: {{ $servicePort.targetPort }}
      name: {{ $servicePort.name }}
    {{- end }}
  selector:
    {{- include "devops-processor.selectorLabels" . | nindent 4 }}
