apiVersion: v1
kind: PersistentVolume
metadata:
  name: customapi-pv
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: stage-knowhow
    name: customapi-pvc

