apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-credentials
  namespace: uat-knowhow
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: speedtools-azurekeyvault #refers to the SecretStore object
    kind: SecretStore
  target:
    name: knowhow-config-credentials #name of the k8s native secret
    creationPolicy: Owner
  data:
  - secretKey: uatknhdbusername
    remoteRef:
      key: uatknhdbusername #Azure Vault secret key
  - secretKey: uatknhdbpassword
    remoteRef:
      key: uatknhdbpassword #Azure Vault secret key
  - secretKey: uatknhdbconnectionstring
    remoteRef:
      key: uatknhdbconnectionstring #Azure Vault secret key
  - secretKey: uatknhdbhost
    remoteRef:
      key: uatknhdbhost #Azure Vault secret key
  - secretKey: knowhow-auth-secret
    remoteRef:
      key: knowhow-auth-secret #Azure Vault secret key
  - secretKey: knowhowaesEncryptionKey
    remoteRef:
      key: knowhowaesEncryptionKey
  - secretKey: uat-repo-tool-api-key
    remoteRef:
      key: uat-repo-tool-api-key
