apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: wildcard-tools-publicos-sapient-com
  name: jenkins 
  namespace: stage-build
spec:
  ingressClassName: azure-application-gateway
  rules:
  - host: buildspeedtool.publicissapient.com 
    http:
      paths:
      - backend:
          service:
            name: jenkins
            port:
              number: 8080
        path: /
        pathType: Exact
status:
  loadBalancer:
    ingress:
    - ip: 13.94.97.252
