apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: stage-knowhow
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki.stage-dashboard.svc.cluster.local:3100/loki/api/v1/push

    scrape_configs:
      - job_name: customapi-promtail
        static_configs:
          - targets:
              - localhost
            labels:
              app: customapi-promtail
              __path__: /app/logs/*.log
