apiVersion: apps/v1
kind: Deployment
metadata:
  name: knowhow-ui
  namespace: {{ .Values.env}}knowhow
  labels:
    app: knowhow-ui
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: knowhow-ui
  template:
    metadata:
      labels:
        app: knowhow-ui
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "knowhow-ui.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: knowhow-ui
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          # env:
          #   - name: API_HOST
          #     value: customapi
          #   - name: API_PORT
          #     value: "8080"
          #   - name: ENVIRONMENT
          #     value: "prod"
          #   - name: CENTRAL_LOGIN_URL
          #     value: "https://{{ .Values.env}}-authnauth.tools.publicis.sapient.com"
          #   - name: MAP_URL
          #     value: "https://preprod-assessmentplatform.tools.publicis.sapient.com"
          #   - name: RETROS_URL
          #     value: "https://{{ .Values.env}}-retrospective.tools.publicis.sapient.com"
          envFrom:
          - configMapRef:
              name: {{ .Values.configmapname }}
          readinessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
