apiVersion: v1
kind: Service
metadata:
  name: {{ include "knowhow-ui.fullname" . }}
  namespace: {{ .Values.env}}-knowhow
  labels:
    {{- include "knowhow-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https  # Name for the HTTPS port
      protocol: TCP
      port: 443
      targetPort: 443
  selector:
    {{- include "knowhow-ui.selectorLabels" . | nindent 4 }}
