apiVersion: v1
kind: Service
metadata:
  name: knowhow-ui
  namespace: {{ .Values.env}}-knowhow
spec:
  selector:
    app: knowhow-ui
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
