apiVersion: apps/v1
kind: Deployment
metadata:
  name: customapi
  namespace: {{ .Values.env}}knowhow
  labels:
    app: customapi
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: customapi
  template:
    metadata:
      labels:
        app: customapi
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "knowhow-customapi.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: customapi
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: versionnumber
              value: {{.Values.image.tag | default .Chart.AppVersion}}
            - name: spring.data.mongodb.uri
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env}}knhdbconnectionstring
                  key: {{ .Values.env}}knhdbconnectionstring
            # - name: spring.data.mongodb.host
            #   valueFrom:
            #     secretKeyRef:
            #       name: knowhow-config-credentials
            #       key: {{ .Values.env}}knhdbhost
            - name: repoToolAPIKey
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env}}-repo-tool-api-key
                  key: {{ .Values.env}}-repo-tool-api-key
            - name: aesEncryptionKey
              valueFrom:
                secretKeyRef:
                  name: knowhowaesencryptionkeynew
                  key: knowhowaesencryptionkeynew
            - name: auth.secret
              valueFrom:
                secretKeyRef:
                  name: knowhow-auth-secret
                  key: knowhow-auth-secret

            - name: spring.data.mongodb.username
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env}}knhdbusername
                  key: {{ .Values.env}}knhdbusername
            - name: spring.data.mongodb.password
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env}}knhdbpassword
                  key: {{ .Values.env}}knhdbpassword
            - name: mongock.migration-scan-package
              value: com.publicissapient.kpidashboard.apis.mongock.installation  
            - name: auth.centralAuthBaseURL
              value: "https://{{ .Values.env}}-authnauth.tools.publicis.sapient.com"
          envFrom:
          - configMapRef:
              name: {{ .Values.configmapname }}
          volumeMounts:
            - name: knowhow-secrets-store
              mountPath: "/mnt/{{ .Values.env}}secrets-store"
              readOnly: true
      volumes:
        - name: knowhow-secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "{{ .Values.env}}secretproviderclass"
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
            initialDelaySeconds: 10   # Wait for 10 seconds before starting probes
            periodSeconds: 5  
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
            initialDelaySeconds: 10   # Wait for 10 seconds before starting probes
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

