apiVersion: v1
kind: Service
metadata:
  name: knowhow-customapi
  namespace: {{ .Values.namespace}}
  labels:
    {{- include "knowhow-customapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "knowhow-customapi.selectorLabels" . | nindent 4 }}
