apiVersion: v1
kind: Service
metadata:
  name: customapi
  namespace: {{ .Values.env}}-knowhow
  labels:
    app: customapi
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: customapi
