apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: {{ .Values.env}}-knowhow
  labels:
    {{- include "knowhow-kafka.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "knowhow-kafka.selectorLabels" . | nindent 4 }}
