apiVersion: v1
kind: Service
metadata:
  name: kafka-cluster
  namespace: {{ .Values.env}}-knowhow
spec:
  selector:
    app: kafka-cluster
  ports:
  - port: 9092
    targetPort: 9092
  type: ClusterIP

