auth:
  accountLockedThreshold: 3
  assertingEntityId: https://sts.windows.net/d52c9ea1-7c21-47b1-82a3-33a74b1f74b8/
  authCookieDuration: 3600
  authCookieHttpOnly: true
  authCookieSameSite: SameSite=None
  authCookieSecured: true
  authenticationProviders: SAML,STANDARD
  #Purpose of properties : central auth frontend url/domain Name
  #possible values : https://dev-authnauth.tools.publicis.sapient.com , https://qa-authnauth.tools.publicis.sapient.com
  # https://uat-authnauth.tools.publicis.sapient.com  , http://localhost:3000
  #used in/for : back to frontend redirect
  baseUiUrl: https://dev-authnauth.tools.publicis.sapient.com
  #Purpose of properties : central auth backend url
  #possible values : http://authnauth:8787 , http://localhost:8787
  #used in/for : saml login , redirect and validate request
  baseUrl: http://authnauth:8787
  #Purpose of properties : property used to provide valid origin
  #possible values : String [a-z, A-Z, 0-9]
  #used in/for : CORS
  corsFilterValidOrigin:
    - localhost
    - 127.0.0.1
    - ui
    - dev-authnauth.tools.publicis.sapient.com
    - qa-authnauth.tools.publicis.sapient.com
    - uat-authnauth.tools.publicis.sapient.com
    - local-tengine.tremend.ro
  defaultRedirectToAfterLogin: ${auth.baseUiUrl}/login/status
  defaultRedirectToAfterLogout: ${auth.baseUrl}${server.servlet.context-path}/hello
  domain: tools.publicis.sapient.com
  expirationTime: 172800000
  #Purpose of properties : expose push data api token expiry days limit
  #possible values : number [1-365]
  #used in/for : expose push data api
  exposeAPITokenExpiryDays: 90
  holdingEntityId: spn:bf226903-9d44-4e77-af84-e3ad008442ef
  loginCallback: ${auth.baseUrl}${server.servlet.context-path}/saml/sp/discovery?idp=${auth.assertingEntityId}
  loginSuccessPageFormat: ${auth.baseUiUrl}/status?authToken=%s
  logoutCallback: ${auth.baseUrl}${server.servlet.context-path}/saml/sp/logout?${auth.logoutEmailQueryParam}=%s
  loginView: login_view
  logoutView: logout_view
  logoutEmailQueryParam: email
  mailTemplate:
    Access_Request: Access_Request_Template
    Approve_User_Reject: Approve_User_Reject_Template
    Approve_User_Success: Approve_User_Success_Template
    Forgot_Password: Forgot_Password_Template
    Pre_Approval: Pre_Approval_Template
    User_Verification: User_Verification_Template
    User_Verification_Failed: User_Verification_Failed_Template
  mailemplate:
    Submit_Feedback: Feedback_Submit_Template
  nameId: urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress
  notificationSubject:
    accessRequest: New access request for KnowHOW
    approvalRequest: Approval Request for KnowHow
    failedApproval: 'KnowHOW: User Approval Rejected'
    forgotPassword: Password Reset Request
    preApproval: 'KnowHOW: New user request'
    userVerification: User Verification Request
    userVerificationFailed: User Verification Token Expired
  samlMaxAuthenticationAgeMillis: 604800000
  secret: 3106dd9eee424487884363ce026ea979
  subDomainCookie: true
  ssoLogin: false
  auth-endpoints:
    authenticated-endpoints:
      - '**'
    public-endpoints:
      - '/sso-login'
      - '/sso-logout-view'

flag:
  mailWithoutKafka: false
forgotPassword:
  #Purpose of properties : property used to expire forgot password
  #possible values : number [1-20]
  #used in/for : forgot password functionality - In Minute
  expiryInterval: 30
  #Set this property only for local setup(eg. 8787). Empty for server.
  serverPort: ''
  #uiHost will be "localhost" for local setup and empty for server
  uiHost: ''
  #Set this property only for local setup (eg. 3000). Empty for server.
  uiPort: ''

kafka:
  mailtopic: mail-topic

logging:
  level:
    root: info
  logType: both

notification:
  #Purpose of properties : property used to provide smtp service sent mail
  #possible values : development, production
  #used in/for : sent mail
  env: development
  #Purpose of properties : property used to provide if any instance want to disable mail
  #possible values : true for mail sent , false for disable
  #used in/for : sent mail
  switch: true

server:
  port: 8787
  servlet:
    context-path: /api
  tomcat:
    redirect-context-root: false
spring:
  datasource:
    password: sapient@123
    url: jdbc:postgresql://authdb:5432/authNauth
    username: authdb
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: auth
  kafka:
    producer:
      bootstrap-servers: kafka:9092
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    saml2:
      serviceProvider:
        alias: ps-ad
        basePath: ${auth.baseUrl}${server.servlet.context-path}
        encryptAssertions: false
        entityId: spn:bf226903-9d44-4e77-af84-e3ad008442ef
        keys:
          active:
            name: sp-signing-key-1
        nameIds: urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress
        providers:
          -   alias: ps-ad
              authenticationRequestBinding: urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST
              metadata: https://login.microsoftonline.com/d52c9ea1-7c21-47b1-82a3-33a74b1f74b8/federationmetadata/2007-06/federationmetadata.xml?appid=bf226903-9d44-4e77-af84-e3ad008442ef
              skipSslValidation: true
        signMetadata: false
        signRequests: false
        singleLogoutEnabled: true
        wantAssertionsSigned: true

ui:
  #Purpose of properties : property used to reset link open via mail and redirect to UI
  registerPath: /register
  #Purpose of properties : property used to reset link open via mail and redirect to UI
  resetPath: /reset-password?resetToken=
  #Purpose of properties : property used to verify user via mail and redirect to UI
  validateUser: /api/verifyUser?token=

verifyUser:
  #Purpose of properties : property used for user token expiration before verification
  #possible values : number [1-20]
  #used in/for : user verification functionality - In days
  tokenExpiryDays: 30
