auth:
  cookie:
    isSameSite: false
    isSecure: false
    domain: localhost

  forgotPassword:
    #Purpose of properties : property used to expire forgot password
    #possible values : number [1-20]
    #used in/for : forgot password functionality - In Minute
    expiryInterval: 30
    serverPort: 8787
    uiHost: http://localhost
    uiPort: 3000

  #Purpose of properties : central auth frontend url/domain Name
  #possible values : https://dev-authnauth.tools.publicis.sapient.com , http://localhost:3000
  #used in/for : back to frontend redirect
  baseUiUrl: http://localhost:3000

  #Purpose of properties : central auth backend url
  #possible values : http://authnauth:8787 , http://localhost:8787
  #used in/for : saml login , redirect and validate request
  baseUrl: http://localhost:8787

  mailWithoutKafka: true

notification:
  #Purpose of properties : property used to provide smtp service sent mail
  #possible values : development, production
  #used in/for : sent mail
  env: development
  #Purpose of properties : property used to provide if any instance want to disable mail
  #possible values : true for mail sent , false for disable
  #used in/for : sent mail
  switch: false

logging:
  level:
    root: INFO

spring:
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/authdblocal
    username: postgres
