apiVersion: v1
kind: Service
metadata:
  name: {{ include "debbie-django.fullname" . }}
  namespace: {{ .Values.env}}-knowhow
  labels:
    {{- include "debbie-django.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "debbie-django.selectorLabels" . | nindent 4 }}
