version: "2"
services:
  authdb:
    image: psknowhow/authdb:<TAG VERSION>
    tty: true
    container_name: authdb
    restart: always
    cpus: 0.2
    mem_limit: 2048m
    mem_reservation: 1024m
    volumes:
      - authdata:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - HOST=<Host IP>
      - POSTGRES_USER=<DB USER NAME>
      - POSTGRES_PASSWORD=<DB PASSWORD>
      - POSTGRES_DB=<DB NAME >
    networks:
      - Network_auth

  authnauth:
    image: psknowhow/authnauth:<TAG VERSION>
    depends_on:
      - authdb
    restart: always
    tty: true
    cpus: 0.2
    container_name: authnauth
    mem_limit: 2048m
    mem_reservation: 1024m
    environment:
      - auth.baseUrl=https://<DNS>
      - auth.baseUiUrl=https://<DNS>
      - auth.secret=<add auth secret>
      - forgotPassword.uiHost=https://<DNS>
      - auth.corsFilterValidOrigin=https://<DNS>
      - spring.datasource.password=<DB PASSWORD>
      - spring.datasource.username=<POSTGRES_USER>
      - auth.holdingEntityId=
      - auth.assertingEntityId=
      - auth.alias=
      - auth.samlLoginUrl=
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - authdb:authdb
    networks:
      - Network_auth

  authnauth-ui:
    image: psknowhow/authnauth-ui:<TAG VERSION>
    depends_on:
      - authdb
      - authnauth
    restart: always
    tty: true
    cpus: 0.2
    container_name: authnauth-ui
    mem_limit: 512m
    mem_reservation: 256m
    ports:
      - 443:443
    environment:
      - REACT_APP_DNS=https://<DNS>
      - REACT_APP_PSKnowHOW=https://<KNOWHOW DNS>
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - authdb:authdb
    networks:
      - Network_auth

volumes:
  authdata:

networks:
  Network_auth:
    driver: bridge
    ipam:
      config:
        - subnet: 192.167.1.0/24