version: "2"
services:
  # authdb:
  #   image: psknowhow/authdb:<TAG VERSION>
  #   tty: true
  #   container_name: authdb
  #   restart: always
  #   cpus: 0.2
  #   mem_limit: 2048m
  #   mem_reservation: 1024m
  #   volumes:
  #     - authdata:/var/lib/postgresql/data
  #     - /etc/localtime:/etc/localtime:ro
  #   environment:
  #    # add environment variables as mentioned here https://psknowhow.atlassian.net/wiki/spaces/PSKNOWHOW/pages/45711363/Docker+Environmental+variables#AuthnAuth-Specific-Variables%3A-Use-Only-When-Deploying-Knowhow-with-Auth-Application
  #   networks:
  #     - Network_auth


  ###   If you are not running postgres as scp processor you can uncomment the above "authdb" docker service.  
  
  authnauth:
    image: psknowhow/authnauth:<TAG VERSION>
    depends_on:
      - authdb
    restart: always
    tty: true
    cpus: 0.2
    container_name: authnauth
    mem_limit: 2048m
    mem_reservation: 1024m
    environment:
      # add environment variables as mentioned here https://psknowhow.atlassian.net/wiki/spaces/PSKNOWHOW/pages/45711363/Docker+Environmental+variables#AuthnAuth-Specific-Variables%3A-Use-Only-When-Deploying-Knowhow-with-Auth-Application
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - authdb:authdb
    networks:
      - Network_auth

  authnauth-ui:
    image: psknowhow/authnauth-ui:<TAG VERSION>
    depends_on:
      - authdb
      - authnauth
    restart: always
    tty: true
    cpus: 0.2
    container_name: authnauth-ui
    mem_limit: 512m
    mem_reservation: 256m
    ports:
      - 443:443
    environment:
      # add environment variables as mentioned here https://psknowhow.atlassian.net/wiki/spaces/PSKNOWHOW/pages/45711363/Docker+Environmental+variables#AuthnAuth-Specific-Variables%3A-Use-Only-When-Deploying-Knowhow-with-Auth-Application
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - authdb:authdb
    networks:
      - Network_auth

volumes:
  authdata:

networks:
  Network_auth:
    driver: bridge
    ipam:
      config:
        - subnet: <Unique Pvt CIDR example 192.167.1.0/24>
