version: "2"
services:
  authdb:
    image: psknowhow/authdb:<TAG VERSION>
    tty: true
    container_name: authdb
    restart: always
    cpus: 0.2
    mem_limit: 2048m
    mem_reservation: 1024m
    volumes:
      - authdata:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - HOST=<Host IP>
      - POSTGRES_USER=<DB USER NAME>
      - POSTGRES_PASSWORD=<DB PASSWORD>
      - POSTGRES_DB=<DB NAME >
    networks:
      - Network_knowhow

  authnauth:
    image: psknowhow/authnauth:<TAG VERSION>
    depends_on:
      - authdb
    restart: always
    tty: true
    cpus: 0.2
    container_name: authnauth
    mem_limit: 2048m
    mem_reservation: 1024m
    environment:
      - auth.baseUrl=https://<DNS>
      - auth.baseUiUrl=https://<DNS>
      - auth.secret=3106dd9eee424487884363ce026ea979
      - forgotPassword.uiHost=https://<DNS>
      - auth.corsFilterValidOrigin=https://<DNS>
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - authdb:authdb
    networks:
      - Network_knowhow

  authnauth-ui:
    image: psknowhow/authnauth-ui:<TAG VERSION>
    depends_on:
      - authdb
      - authnauth
    restart: always
    tty: true
    cpus: 0.2
    container_name: authnauth-ui
    mem_limit: 512m
    mem_reservation: 256m
    ports:
      - 443:443
    environment:
      - REACT_APP_DNS=https://<DNS>
      - REACT_APP_PSKnowHOW=https://<KNOWHOW DNS>
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - authdb:authdb
    networks:
      - Network_knowhow

  MongoDB:
    image: psknowhow/mongo-base:5.0.18
    tty: true
    container_name: mongodb
    ports:
      - 27017:27017
    restart: on-failure
    volumes:
      - mongodbvol:/data/db
      - mongodbvol:/data/logs
    environment:
      - MONGO_INITDB_ROOT_USERNAME=<DB ROOT USERNAME>
      - MONGO_INITDB_ROOT_PASSWORD=<DB ROOT PASSWORD>
      - MONGODB_APPLICATION_USER=<DB APPLICATION USERNAME>
      - MONGODB_APPLICATION_PASS=<DB APPLICATION PASSWORD>
    networks:
      - Network_knowhow

  CustomAPI:
    image: psknowhow/customapi:latest
    depends_on:
      - MongoDB
    restart: on-failure
    tty: true
    container_name: customapi
    mem_limit: 4096m
    mem_reservation: 1024m
    ports:
      - 8080:8080
    volumes:
      - customapivol:/app/logs
      - customapivol:/app/properties/
      - customapivol:/app/offline_data/
      - customapivol:/app/certs/
      - /etc/hosts:/etc/hosts
    environment:
      - CONFIG_LOCATION=file:/app/properties/customapi.properties
      - forgotPassword.uiHost=<Your-Public-IP>or<Your-DNS>
      - corsFilterValidOrigin=<Your-Public-IP>,localhost,<Your-DNS>
      - versionnumber=7.0.0
      - JAVA_OPTS-XX:+HeapDumpOnOutOfMemoryError
      - spring.data.mongodb.uri=mongodb://<DB USER NAME>:<DB PASSWORD>@mongodb:27017/kpidashboard
      # If your DB is hosted on atlas pass the Connection string in spring.data.mongodb.atlas.uri and mongodb.connection.atlas to "true"
      - spring.data.mongodb.atlas.uri=mongodb+srv://<USER NAME>:<TOKEN>@<CLUSTER URL>.mongodb.net/kpidashboard
      # mongodb.connection.atlas Toggle to determine whether to use local MongoDB or MongoDB Atlas
      - mongodb.connection.atlas=false
      - aesEncryptionKey=<Your AES Encryption KEY here>
      - auth.secret=<Your Auth Secret>
    links:
      - MongoDB:mongodb
    networks:
      - Network_knowhow

  UI:
    image: psknowhow/ui:latest
    depends_on:
      - CustomAPI
    restart: on-failure
    tty: true
    container_name: ui
    mem_limit: 1024m
    mem_reservation: 256m
    ports:
      - 88:80
      - 444:443
    volumes:
      - uivol:/var/log/nginx
      #- uivol:/etc/ssl/certs/ # If you have your SSL certificate uncomment it and copy to /app/apps/certs directory 
    links:
      - CustomAPI:customapi
    environment:
      - API_HOST=customapi
      - API_PORT=8080
      - DNS_SSL=<Your-IP>
    networks:
      - Network_knowhow

  jira-processor:
    image: psknowhow/jira-processor:latest
    depends_on:
      - MongoDB
    restart: on-failure
    tty: true
    container_name: jira-processor
    mem_limit: 4096m
    mem_reservation: 1024m
    volumes:
      - jira-processorvol:/app/logs
      - jira-processorvol:/app/properties/
      - jira-processorvol:/app/offline_data
      - /etc/hosts:/etc/hosts
    environment:
      - JAVA_OPTS=-XX:+HeapDumpOnOutOfMemoryError
      - spring.data.mongodb.uri=mongodb://<DB USER NAME>:<DB PASSWORD>@mongodb:27017/kpidashboard
      # If your DB is hosted on atlas pass the Connection string in spring.data.mongodb.atlas.uri and mongodb.connection.atlas to "true"
      - spring.data.mongodb.atlas.uri=mongodb+srv://<USER NAME>:<TOKEN>@<CLUSTER URL>.mongodb.net/kpidashboard
      # mongodb.connection.atlas Toggle to determine whether to use local MongoDB or MongoDB Atlas
      - mongodb.connection.atlas=false
      - aesEncryptionKey=<Your AES Encryption KEY here>
    links:
      - MongoDB:mongodb
    networks:
      - Network_knowhow

  devops-processor:
    image: psknowhow/devops-processor:latest
    depends_on:
      - MongoDB
    restart: on-failure
    tty: true
    container_name: devops-processor
    mem_limit: 8192m
    mem_reservation: 2048m
    volumes:
      - devops-processorvol:/app/logs
      - devops-processorvol:/app/properties/
      - devops-processorvol:/app/offline_data
      - devops-processorvol:/app/certs/
      - /etc/hosts:/etc/hosts
    environment:
      - JAVA_OPTS=-XX:+HeapDumpOnOutOfMemoryError
      - spring.data.mongodb.uri=mongodb://<DB USER NAME>:<DB PASSWORD>@mongodb:27017/kpidashboard
      # If your DB is hosted on atlas pass the Connection string in spring.data.mongodb.atlas.uri and mongodb.connection.atlas to "true"
      - spring.data.mongodb.atlas.uri=mongodb+srv://<USER NAME>:<TOKEN>@<CLUSTER URL>.mongodb.net/kpidashboard
      # mongodb.connection.atlas Toggle to determine whether to use local MongoDB or MongoDB Atlas
      - mongodb.connection.atlas=false
      - aesEncryptionKey=<Your AES Encryption KEY here>
    links:
      - MongoDB:mongodb
    networks:
      - Network_knowhow

  azure-board-processor:
    image: psknowhow/azure-board-processor:latest
    restart: on-failure
    depends_on:
      - MongoDB
    tty: true
    container_name: azure-board-processor
    mem_limit: 1024m
    mem_reservation: 512m
    volumes:
      - azure-board-processorvol:/app/logs
      - azure-board-processorvol:/app/properties/
      - azure-board-processorvol:/app/offline_data
      - /etc/hosts:/etc/hosts
    environment:
      - JAVA_OPTS=-XX:+HeapDumpOnOutOfMemoryError
      - spring.data.mongodb.uri=mongodb://<DB USER NAME>:<DB PASSWORD>@mongodb:27017/kpidashboard
      # If your DB is hosted on atlas pass the Connection string in spring.data.mongodb.atlas.uri and mongodb.connection.atlas to "true"
      - spring.data.mongodb.atlas.uri=mongodb+srv://<USER NAME>:<TOKEN>@<CLUSTER URL>.mongodb.net/kpidashboard
      # mongodb.connection.atlas Toggle to determine whether to use local MongoDB or MongoDB Atlas
      - mongodb.connection.atlas=false
      - aesEncryptionKey=<Your AES Encryption KEY here>
    links:
      - MongoDB:mongodb
    networks:
      - Network_knowhow

  azure-pipeline-repo:
    image: psknowhow/azure-pipeline-repo:latest
    restart: on-failure
    depends_on:
      - MongoDB
    tty: true
    container_name: azure-pipeline-repo
    mem_limit: 2048m
    mem_reservation: 1024m
    volumes:
      - azure-pipeline-repovol:/app/logs
      - azure-pipeline-repovol:/app/properties/
      - azure-pipeline-repovol:/app/offline_data
      - azure-pipeline-repovol:/app/certs/
      - /etc/hosts:/etc/hosts
    environment:
      - JAVA_OPTS=-XX:+HeapDumpOnOutOfMemoryError
      - spring.data.mongodb.uri=mongodb://<DB USER NAME>:<DB PASSWORD>@mongodb:27017/kpidashboard
      # If your DB is hosted on atlas pass the Connection string in spring.data.mongodb.atlas.uri and mongodb.connection.atlas to "true"
      - spring.data.mongodb.atlas.uri=mongodb+srv://<USER NAME>:<TOKEN>@<CLUSTER URL>.mongodb.net/kpidashboard
      # mongodb.connection.atlas Toggle to determine whether to use local MongoDB or MongoDB Atlas
      - mongodb.connection.atlas=false
      - aesEncryptionKey=<Your AES Encryption KEY here>
    links:
      - MongoDB:mongodb
    networks:
      - Network_knowhow

  kafka-consumers:
    image: psknowhow/kafka-consumers:latest
    restart: on-failure
    depends_on:
      - MongoDB
    tty: true
    container_name: kafka-consumers
    volumes:
      - kafka-consumersvol:/app/properties/
    mem_limit: 2048m
    mem_reservation: 1024m
    ports:
      - 50020:50020
    links:
      - MongoDB:mongodb
    networks:
      - Network_knowhow
  kafka:
    image: bitnami/kafka:3.2.1
    restart: on-failure
    depends_on:
      - zookeeper
    tty: true
    container_name: kafka
    mem_limit: 2048m
    mem_reservation: 1024m
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    ports:
      - 9092:9092
    links:
      - MongoDB:mongodb
    networks:
      - Network_knowhow
  zookeeper:
    image: zookeeper:3.8.0
    container_name: zookeeper
    mem_limit: 2048m
    mem_reservation: 1024m
    restart: always
    ports:
      - "2181:2181"
    networks:
      - Network_knowhow
volumes:
  kafka-consumersrvol:
  azure-board-processorvol:
  azure-pipeline-repovol:
  devops-processorvol:
  jira-processorvol:
  uivol:
  customapivol:
  mongodbvol:
  authdata:

networks:
  Network_knowhow:
    driver: bridge
    ipam:
      config:
        - subnet: 192.167.1.0/24