apiVersion: v1
kind: Service
metadata:
  name: azure-pipeline-repo
  namespace: {{ .Values.env}}-knowhow
  labels:
    app: azure-pipeline-repo
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $servicePort := .Values.servicePorts }}
    - protocol: TCP
      port: {{ $servicePort.port }}
      targetPort: {{ $servicePort.targetPort }}
      name: {{ $servicePort.name }}
    {{- end }}
  selector:
    app: azure-pipeline-repo
