apiVersion: v1
kind: ConfigMap
metadata:
  name: debbie-config
  namespace: {{.Values.namespace}}
data:
  # property-like keys; each key maps to a simple value
  POSTGRES_DB: "debbie"
  DEBUG: "True"
  DEBUG_TOOLBAR: "True"
  ALLOWED_HOSTS: "*"
  CORS_ORIGIN_WHITELIST: "http://localhost"
  RESULT_SEND_TYPE: "mq"
  RABBITMQ_DEFAULT_USER: "admin"
  RABBITMQ_DEFAULT_VHOST: "debbie"
  RABBIT_BROKER_HOST: "debbie-rabbitmq"
  RABBIT_BROKER_PORT: "5672"
  RABBIT_QUEUE: "repos"
  PYTHONPATH: "${PYTHONPATH}:/code/utils:/code/scanner:/code/mq:/code"
  RUN_SONARQUBE: "True"
  GIT_PYTHON_TRACE: "1"
  GIT_PROCESS_ONLY_ONE_COMMIT: "true"
  GIT_WITHOUT_MODIFICATIONS: "true"
  EMAIL_USE_TLS: "True"
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: "587"
  EMAIL_HOST_USER: "user@user.com"
  GITLAB_URL: "https://gitlab.tremend.com"
  TENGINE_QUERY_USERNAME: "xyz"
  BASE_HOST_URL: "https://4bdf-89-136-52-54.ngrok-free.app"
  FE_CLEAR_CACHE_APIS: "http://customapi:8080/api/cache/clearCache/toolItemMap,http://customapi:8080/api/cache/clearCache/bitbucketKpiCache"
