apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.env }}-debbie-credentials
  namespace: {{.Values.namespace}}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: speedtools-azurekeyvault #refers to the SecretStore object
    kind: SecretStore
  target:
    name: {{.Values.secretname}} #name of the k8s native secret
    creationPolicy: Owner
  data:
  - secretKey: {{ .Values.env }}debbieuser
    remoteRef:
      key: {{ .Values.env }}debbieuser #Azure Vault secret key
  - secretKey: {{ .Values.env }}rabbitpass
    remoteRef:
      key: {{ .Values.env }}rabbitpass
  - secretKey: {{ .Values.env }}-debbie-secret-key
    remoteRef:    
      key: {{ .Values.env}}-debbie-secret-key
  - secretKey: {{ .Values.env }}debbiepassword
    remoteRef:
      key: {{.Values.env}}debbiepassword
  - secretKey: debbiemailhostpass
    remoteRef:
      key: debbiemailhostpass
  - secretKey: tenginequerypass
    remoteRef:
      key: tenginequerypass
  - secretKey: debbietengineauthtoken
    remoteRef:
      key: debbietengineauthtoken
  - secretKey: {{.Values.env}}-debbie-db-url
    remoteRef:
      key: {{.Values.env}}-debbie-db-url
  - secretKey: {{.Values.env}}-debbie-internal-key 
    remoteRef:
      key: {{.Values.env}}-debbie-internal-key  
