apiVersion: v1
kind: Service
metadata:
  name: customapi
  labels:
    app: customapi
spec:
  type: {{ .Values.service.backendtype }}
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: customapi
