{{- if and .Values.authNauthNSCMDB.enabled (eq .Values.authNauthNSCMDB.volumeType "efs") }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-efs-pv
spec:
  capacity:
    storage: {{ .Values.authNauthNSCMDB.storage }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.authNauthNSCMDB.accessMode }}
  storageClassName: {{ .Values.authNauthNSCMDB.efs.storageClassName }}
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.authNauthNSCMDB.efs.volumeHandle }}
{{- end }}

{{- if and .Values.authNauthNSCMDB.enabled (eq .Values.authNauthNSCMDB.volumeType "azureDisk") }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-azuredisk-pv
  annotations:
    pv.kubernetes.io/provisioned-by: disk.csi.azure.com
spec:
  capacity:
    storage: {{ .Values.authNauthNSCMDB.storage }}
  accessModes:
    - {{ .Values.authNauthNSCMDB.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.authNauthNSCMDB.azureDisk.storageClassName}}
  csi:
    driver: disk.csi.azure.com
    volumeHandle: {{ .Values.authNauthNSCMDB.azureDisk.volumeHandle }}
    volumeAttributes:
      fsType: ext4
{{- end }}
