{{- if .Values.authNauthApp.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: authnauth-ui
  labels:
    app: authnauth-ui
spec:
  type: {{ .Values.service.uitype }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: authnauth-ui
{{- end }}