{{- if .Values.DevOpsApp.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-processor
  labels:
    app: devops-processor
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: devops-processor
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: devops-processor
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "knowhow-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.devopsrepository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 50001
              protocol: TCP
            - containerPort: 50002
              protocol: TCP
            - containerPort: 50003
              protocol: TCP
            - containerPort: 50006
              protocol: TCP
            - containerPort: 50007
              protocol: TCP
            - containerPort: 50011
              protocol: TCP
            - containerPort: 50012
              protocol: TCP
            - containerPort: 50014
              protocol: TCP
            - containerPort: 50019
              protocol: TCP
            - containerPort: 50020
              protocol: TCP
            - containerPort: 50022
              protocol: TCP
            - containerPort: 50023
              protocol: TCP
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 300
            periodSeconds: 40
            successThreshold: 1
            tcpSocket:
              port: 50022
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 300
            periodSeconds: 40
            successThreshold: 1
            tcpSocket:
              port: 50022
            timeoutSeconds: 1
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}