{{- if .Values.mongodb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: mongodb
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "knowhow-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: mongodb
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.mongorepository }}:{{ .Values.image.mongodbtag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 27017
              protocol: TCP
          env:
            {{- range .Values.mongodb.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          volumeMounts:
            - mountPath: /data/db
              name: psknowhow-db-data-volume
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 45
            periodSeconds: 20
            successThreshold: 1
            tcpSocket:
              port: 27017
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 45
            periodSeconds: 20
            successThreshold: 1
            tcpSocket:
              port: 27017
            timeoutSeconds: 1
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if eq .Values.mongodb.volumeType "hostPath" }}
        - name: psknowhow-db-data-volume
          hostPath:
            path: {{ .Values.mongodb.hostPath.path }}
            type: DirectoryOrCreate
        {{- else if eq .Values.mongodb.volumeType "azureDisk" }}
        - name: psknowhow-db-data-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-azuredisk-pvc
        {{- else if eq .Values.mongodb.volumeType "efs" }}
        - name: psknowhow-db-data-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-efs-pvc
        {{- else }}
        - name: psknowhow-db-data-volume
          persistentVolumeClaim:
            claimName: {{ .Values.mongodb.pvcName }}
        {{- end }}
{{- end }}
