{{- if and .Values.mongodb.enabled (eq .Values.mongodb.volumeType "efs") }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-efs-pv
spec:
  capacity:
    storage: {{ .Values.mongodb.storage }}
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.mongodb.accessMode }}
  storageClassName: {{ .Values.mongodb.efs.storageClassName }}
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.mongodb.efs.fileSystemId }}
{{- end }}

{{- if and .Values.mongodb.enabled (eq .Values.mongodb.volumeType "azureDisk") }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-azuredisk-pv
  annotations:
    pv.kubernetes.io/provisioned-by: disk.csi.azure.com
spec:
  capacity:
    storage: {{ .Values.mongodb.storage }}
  accessModes:
    - {{ .Values.mongodb.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.mongodb.azureDisk.storageClassName}}
  csi:
    driver: disk.csi.azure.com
    volumeHandle: {{ .Values.mongodb.azureDisk.volumeHandle }}
    volumeAttributes:
      fsType: ext4
{{- end }}
