{{- if and .Values.mongodb.enabled (not (eq .Values.mongodb.volumeType "hostPath")) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: psknowhow-db-pv
  labels:
    type: {{ .Values.mongodb.volumeType }}
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  {{- if eq .Values.mongodb.volumeType "azureDisk" }}
  azureDisk:
    diskName: {{ .Values.mongodb.azureDisk.diskName }}
    diskUri: {{ .Values.mongodb.azureDisk.diskUri }}
  {{- else if eq .Values.mongodb.volumeType "awsEbs" }}
  awsElasticBlockStore:
    volumeID: {{ .Values.mongodb.awsEbs.volumeID }}
    fsType: {{ .Values.mongodb.awsEbs.fsType }}
  {{- end }}
{{- end }}
