apiVersion: v1
kind: Service
metadata:
  name: knowhow-ui
  labels:
    app: knowhow-ui
spec:
  type: {{ .Values.service.uitype }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: knowhow-ui
